name: Android CI

on:
  push:
    branches: [ main, unit-test ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: rename sample auth xml file
      run: mv app/src/main/res/values/.sample_auth.xml app/src/main/res/values/auth.xml
    - name: Build with Gradle
      run: ./gradlew build
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
