name: Build-LaTeX

on:
  push:
    branches: [ documentation ]

jobs:
  build-tex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: dhbw_doc/sources
          root_file: |
            legacy_code.tex
            ddd.tex
            unit-testing.tex
            refactoring.tex
            programming_principles.tex
      - name: Move PDFs
        run: mv dhbw_doc/sources/*.pdf dhbw_doc/
      - uses: EndBug/add-and-commit@v5 
        with:
          add: '*.pdf'
          message: 'Build LaTeX'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
